/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package capaPresentacio.views;

import javax.swing.*;
import java.awt.*;
import capaPresentacio.CtrlPresentacio;

/**
 *
 * @author linhu
 */
public class loginPanel extends javax.swing.JPanel {
    //mainPanel es el panel de loginView
    //parentFrame es la ventana entera de loginView
    private final javax.swing.JPanel mainPanel;
    private final JFrame parentFrame;
    /**
     * Creates new form loginPanel
     */
    public loginPanel(javax.swing.JPanel mainPanel, JFrame parentFrame) {
        this.mainPanel = mainPanel;
        this.parentFrame = parentFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        inputPanel = new javax.swing.JPanel();
        usernameBox = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordBox = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        signupButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(237, 224, 212));
        setLayout(new java.awt.GridBagLayout());

        inputPanel.setBackground(new java.awt.Color(204, 255, 204));
        inputPanel.setLayout(new java.awt.GridLayout(2, 0));

        usernameBox.setBackground(new java.awt.Color(237, 224, 212));
        usernameBox.setLayout(new java.awt.GridLayout(2, 0));

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(127, 85, 57));
        usernameLabel.setText("Nom d'usuari");
        usernameBox.add(usernameLabel);

        usernameField.setForeground(new java.awt.Color(127, 85, 57));
        usernameField.setBorder(null);
        usernameBox.add(usernameField);

        inputPanel.add(usernameBox);

        passwordBox.setBackground(new java.awt.Color(237, 224, 212));
        passwordBox.setLayout(new java.awt.GridLayout(2, 0));

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(127, 85, 57));
        passwordLabel.setText("Contrasenya");
        passwordBox.add(passwordLabel);

        passwordField.setForeground(new java.awt.Color(127, 85, 57));
        passwordField.setBorder(null);
        passwordBox.add(passwordField);

        inputPanel.add(passwordBox);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 40;
        add(inputPanel, gridBagConstraints);

        loginButton.setBackground(new java.awt.Color(171, 148, 126));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginButton.setForeground(new java.awt.Color(237, 224, 212));
        loginButton.setText("Inicia Sessió");
        loginButton.setToolTipText("");
        loginButton.setBorder(null);
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        add(loginButton, gridBagConstraints);

        signupButton.setBackground(new java.awt.Color(171, 148, 126));
        signupButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signupButton.setForeground(new java.awt.Color(237, 224, 212));
        signupButton.setText("No tens compte? Registra't");
        signupButton.setBorder(null);
        signupButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        add(signupButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = usernameField.getText();
        String password = new String(passwordField.getPassword());
        try {
            CtrlPresentacio.login(username, password);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            return;
        }

        //crea ventana principal del juego
        mainView mv = new mainView();
        mv.setVisible(true);
        //elimina la ventana de login
        this.parentFrame.dispose();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        //cambia la pantalla a la de crear cuenta
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "signup");
    }//GEN-LAST:event_signupButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel inputPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel passwordBox;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton signupButton;
    private javax.swing.JPanel usernameBox;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
