/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package capaPresentacio.views;

import capaDomini.excepcions.ExcepcioKenken;
import capaPresentacio.CtrlPresentacio;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.TreeSet;

/**
 *
 * @author linhu
 */
public class partidaPanel extends javax.swing.JPanel {
    
    boolean modoNotas;
    private final Kenken kenken;
    javax.swing.JToggleButton[] buttonArray;
    private final CardLayout cardLayout;
    private final JPanel mainPanel;
    private int midaKenken;
    int pistesRestants;
    
    /** Creates new form partidaPanel */
    public partidaPanel(CardLayout cardLayout, JPanel mainPanel) {
        this.cardLayout = cardLayout;
        this.mainPanel = mainPanel;
        initComponents(); //del netbeans


        //carrega kenken
        List<List<Integer>> cages = CtrlPresentacio.loadKenken();
        kenken = new Kenken(cages, this);
        kenkenPanel0.add(kenken, "kenkenPreview");
        CardLayout cl = (CardLayout)(kenkenPanel0.getLayout());
        cl.show(kenkenPanel0, "kenkenPreview");

        initDefault(); //ini valors default de un joc nou
        initTemporizador(); //crea el temporizador y se actualiza cada segundo
        initNumberPad(); //inicialitza els botons usables del numberpad amb el tamany del kenken
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        toolOptions = new javax.swing.JPanel();
        tempsButton = new javax.swing.JPanel();
        pausaButton = new javax.swing.JButton();
        reanudaButton = new javax.swing.JButton();
        pistaButton = new javax.swing.JButton();
        solucioButton = new javax.swing.JButton();
        acabaPanel = new javax.swing.JPanel();
        guardaButton = new javax.swing.JButton();
        surtButton = new javax.swing.JButton();
        kenkenPanel0 = new javax.swing.JPanel();
        modeOptions = new javax.swing.JPanel();
        valorButton = new javax.swing.JToggleButton();
        notesButton = new javax.swing.JToggleButton();
        numberPad = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        timeLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(237, 224, 212));
        setPreferredSize(new java.awt.Dimension(1080, 655));
        setLayout(new java.awt.GridBagLayout());

        toolOptions.setBackground(new java.awt.Color(237, 224, 212));
        toolOptions.setLayout(new java.awt.GridLayout(0, 1));

        tempsButton.setLayout(new java.awt.CardLayout());

        pausaButton.setBackground(new java.awt.Color(171, 148, 126));
        pausaButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pausaButton.setForeground(new java.awt.Color(237, 224, 212));
        pausaButton.setText("Pausa");
        pausaButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 224, 212)));
        pausaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pausaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausaButtonActionPerformed(evt);
            }
        });
        tempsButton.add(pausaButton, "card2");

        reanudaButton.setBackground(new java.awt.Color(171, 148, 126));
        reanudaButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reanudaButton.setForeground(new java.awt.Color(237, 224, 212));
        reanudaButton.setText("Reanuda");
        reanudaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reanudaButtonActionPerformed(evt);
            }
        });
        tempsButton.add(reanudaButton, "card3");

        toolOptions.add(tempsButton);

        pistaButton.setBackground(new java.awt.Color(171, 148, 126));
        pistaButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pistaButton.setForeground(new java.awt.Color(237, 224, 212));
        pistaButton.setText("Pista");
        pistaButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 224, 212)));
        pistaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pistaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pistaButtonActionPerformed(evt);
            }
        });
        toolOptions.add(pistaButton);

        solucioButton.setBackground(new java.awt.Color(171, 148, 126));
        solucioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        solucioButton.setForeground(new java.awt.Color(237, 224, 212));
        solucioButton.setText("Solució");
        solucioButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 224, 212)));
        solucioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        solucioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solucioButtonActionPerformed(evt);
            }
        });
        toolOptions.add(solucioButton);

        acabaPanel.setLayout(new java.awt.CardLayout());

        guardaButton.setBackground(new java.awt.Color(171, 148, 126));
        guardaButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        guardaButton.setForeground(new java.awt.Color(237, 224, 212));
        guardaButton.setText("Guarda");
        guardaButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 224, 212)));
        guardaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardaButtonActionPerformed(evt);
            }
        });
        acabaPanel.add(guardaButton, "card2");

        surtButton.setBackground(new java.awt.Color(171, 148, 126));
        surtButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        surtButton.setForeground(new java.awt.Color(237, 224, 212));
        surtButton.setText("Surt");
        surtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surtButtonActionPerformed(evt);
            }
        });
        acabaPanel.add(surtButton, "card3");

        toolOptions.add(acabaPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 150;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 40);
        add(toolOptions, gridBagConstraints);

        kenkenPanel0.setBackground(new java.awt.Color(212, 199, 187));
        kenkenPanel0.setPreferredSize(new java.awt.Dimension(100, 100));
        kenkenPanel0.setLayout(new java.awt.CardLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.ipady = 400;
        add(kenkenPanel0, gridBagConstraints);

        modeOptions.setBackground(new java.awt.Color(237, 224, 212));
        modeOptions.setLayout(new java.awt.GridLayout(1, 0));

        valorButton.setBackground(new java.awt.Color(171, 148, 126));
        valorButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valorButton.setForeground(new java.awt.Color(237, 224, 212));
        valorButton.setText("Mode Valors");
        valorButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 224, 212)));
        valorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        valorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorButtonActionPerformed(evt);
            }
        });
        modeOptions.add(valorButton);

        notesButton.setBackground(new java.awt.Color(171, 148, 126));
        notesButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        notesButton.setForeground(new java.awt.Color(237, 224, 212));
        notesButton.setText("Mode Notes");
        notesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 224, 212)));
        notesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesButtonActionPerformed(evt);
            }
        });
        modeOptions.add(notesButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        add(modeOptions, gridBagConstraints);

        numberPad.setBackground(new java.awt.Color(237, 224, 212));
        numberPad.setLayout(new java.awt.GridLayout(3, 0));

        jToggleButton1.setBackground(new java.awt.Color(171, 148, 126));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(237, 224, 212));
        jToggleButton1.setText("1");
        jToggleButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 224, 212)));
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        numberPad.add(jToggleButton1);

        jToggleButton2.setBackground(new java.awt.Color(171, 148, 126));
        jToggleButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(237, 224, 212));
        jToggleButton2.setText("2");
        jToggleButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 224, 212)));
        jToggleButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        numberPad.add(jToggleButton2);

        jToggleButton3.setBackground(new java.awt.Color(171, 148, 126));
        jToggleButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jToggleButton3.setForeground(new java.awt.Color(237, 224, 212));
        jToggleButton3.setText("3");
        jToggleButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 224, 212)));
        jToggleButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        numberPad.add(jToggleButton3);

        jToggleButton4.setBackground(new java.awt.Color(171, 148, 126));
        jToggleButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jToggleButton4.setForeground(new java.awt.Color(237, 224, 212));
        jToggleButton4.setText("4");
        jToggleButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 224, 212)));
        jToggleButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        numberPad.add(jToggleButton4);

        jToggleButton5.setBackground(new java.awt.Color(171, 148, 126));
        jToggleButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jToggleButton5.setForeground(new java.awt.Color(237, 224, 212));
        jToggleButton5.setText("5");
        jToggleButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 224, 212)));
        jToggleButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        numberPad.add(jToggleButton5);

        jToggleButton6.setBackground(new java.awt.Color(171, 148, 126));
        jToggleButton6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jToggleButton6.setForeground(new java.awt.Color(237, 224, 212));
        jToggleButton6.setText("6");
        jToggleButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 224, 212)));
        jToggleButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        numberPad.add(jToggleButton6);

        jToggleButton7.setBackground(new java.awt.Color(171, 148, 126));
        jToggleButton7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jToggleButton7.setForeground(new java.awt.Color(237, 224, 212));
        jToggleButton7.setText("7");
        jToggleButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 224, 212)));
        jToggleButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        numberPad.add(jToggleButton7);

        jToggleButton8.setBackground(new java.awt.Color(171, 148, 126));
        jToggleButton8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jToggleButton8.setForeground(new java.awt.Color(237, 224, 212));
        jToggleButton8.setText("8");
        jToggleButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 224, 212)));
        jToggleButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        numberPad.add(jToggleButton8);

        jToggleButton9.setBackground(new java.awt.Color(171, 148, 126));
        jToggleButton9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jToggleButton9.setForeground(new java.awt.Color(237, 224, 212));
        jToggleButton9.setText("9");
        jToggleButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 224, 212)));
        jToggleButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        numberPad.add(jToggleButton9);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 200;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        add(numberPad, gridBagConstraints);

        timeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(89, 61, 59));
        timeLabel.setText("Time: 00:00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        add(timeLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void initNumberPad() {
        buttonArray = new JToggleButton[]{jToggleButton1, jToggleButton2, jToggleButton3, jToggleButton4, jToggleButton5, jToggleButton6, jToggleButton7, jToggleButton8, jToggleButton9};
        int nOptions = midaKenken;

        for (int i = nOptions; i<9; i++) {
            buttonArray[i].setVisible(false);
        }
    }

    private void initDefault() {
        //mode inicial es modo valores
        valorButton.setSelected(true);
        //comienza modo valores
        modoNotas = false;
        kenken.hideNotas();
        //mida del kenken
        midaKenken = kenken.getMida();
        //nombre de pistes disponibles
        pistesRestants = CtrlPresentacio.getPistesRestants();
        if (pistesRestants == 0) {
            pistaButton.setEnabled(false);
        }
    }

    private void initTemporizador() {
        // Create a Timer that calls an ActionListener every 1000 milliseconds (1 second)
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                timeLabel.setText("Time: " + CtrlPresentacio.getFormattedTime());
            }
        });

        // Start the Timer
        timer.start();
    }

    private int[] getSelectedCell() {
        if (kenken != null) {
            if (kenken.getCurrentCell() != null) {
                int[] cellPosition = new int[2];
                cellPosition[0] = kenken.getCurrentCell().getRow();
                cellPosition[1] = kenken.getCurrentCell().getCol();
                return cellPosition;
            }
        }
        return null; // Return null if no cell is selected
    }

    public void updateNumPad() {
        int[] posCell = getSelectedCell();
        if (posCell != null) {
            if (!modoNotas) {
                int valor = kenken.getCellValue(posCell[0], posCell[1]);
                Component[] componentsNP = numberPad.getComponents();
                for (Component component : componentsNP) {
                    if (component instanceof JToggleButton) {
                        JToggleButton button = (JToggleButton) component;
                        button.setSelected(button.getText().equals(Integer.toString(valor)));
                    }
                }
            }
            else {
                TreeSet<Integer> notas = kenken.getCellNotes(posCell[0], posCell[1]);
                Component[] componentsNP = numberPad.getComponents();
                for (Component component : componentsNP) {
                    if (component instanceof JToggleButton) {
                        JToggleButton button = (JToggleButton) component;
                        button.setSelected(notas.contains(Integer.parseInt(button.getText())));
                    }
                }
            }

        }
    }

    private void numPadPressed(int num) {
        int[] posCell = getSelectedCell();
        int posX = posCell[0];
        int posY = posCell[1];
        javax.swing.JToggleButton button = buttonArray[num-1];
        if (button.isSelected()) {
            if (!modoNotas) {
                boolean acabat = CtrlPresentacio.assignaValor(posX, posY, num); //anade valor a la celda seleccionada
                kenken.hideNota(posX, posY); //elimina la nota del kenken
                kenken.setCellValue(posX, posY, num); //actualiza preview
                if (acabat) {
                    CtrlPresentacio.acabaPartida();
                    int dialogResult = JOptionPane.showConfirmDialog(null, "Enhorabona, has acabat el kenken correctament!", "Game Over", JOptionPane.DEFAULT_OPTION);
                    if (dialogResult == JOptionPane.OK_OPTION) {
                        jocPanel.updateListJocs();
                        cardLayout.show(mainPanel, "jocCard");
                    }
                }
            }
            else {
                if (kenken.getCellValue(posX, posY) == 0) kenken.addNota(posX, posY, num);
            }

        }
        else {
            if (!modoNotas) {
                CtrlPresentacio.desassignaValor(posX, posY, num); //quita valor a la celda seleccionada
                kenken.unsetCellValue(posX, posY); //actualiza preview
                kenken.showNota(posX, posY);
            }
            else kenken.removeNota(posX, posY, num);
        }
    }
    
    private void valorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorButtonActionPerformed
        // TODO cambiar las funciones de los botones
        if (valorButton.isSelected()) {
            modoNotas = false;
            notesButton.setSelected(false);
            kenkenPanel0.setBackground(new java.awt.Color(204, 255, 204));
        }
        else {
            modoNotas = true;
            notesButton.setSelected(true);
            kenken.showNotas();
            kenkenPanel0.setBackground(new java.awt.Color(255, 102, 102));
        }
    }//GEN-LAST:event_valorButtonActionPerformed

    private void notesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notesButtonActionPerformed
        if (notesButton.isSelected()) {
            modoNotas = true;
            valorButton.setSelected(false);
            kenken.showNotas();
            kenkenPanel0.setBackground(new java.awt.Color(255, 102, 102));
        }
        else {
            modoNotas = false;
            valorButton.setSelected(true);
            //kenken.hideNotas();
            kenkenPanel0.setBackground(new java.awt.Color(204, 255, 204));
        }
    }//GEN-LAST:event_notesButtonActionPerformed

    private void pausaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausaButtonActionPerformed
        CtrlPresentacio.pausa();
        pausaButton.setVisible(false); // hide the pause button
        reanudaButton.setVisible(true); // show the resume button

        // Disable all buttons in the buttonArray
        for (JToggleButton button : buttonArray) {
            button.setEnabled(false);
        }
    }//GEN-LAST:event_pausaButtonActionPerformed

    private void pistaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pistaButtonActionPerformed
        try {
            if (kenken.getPista()) {
                pistesRestants = CtrlPresentacio.usaPista();
                if (pistesRestants == 0) pistaButton.setEnabled(false);
            }
            else {
                JOptionPane.showMessageDialog(null, "No tens cap cella seleccionada", "Informació", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (ExcepcioKenken excepcioKenken) {
            throw new RuntimeException("No hi ha cap pista disponible");
        }
    }//GEN-LAST:event_pistaButtonActionPerformed

    private void solucioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solucioButtonActionPerformed
        try {
            kenken.showSolution();
            CtrlPresentacio.pausa(); //pausa temps
            disableButtons(); //deshabilita numpad
            acabaPanel.setLayout(new CardLayout());
            acabaPanel.add(surtButton, "surtCard");
            ((CardLayout) acabaPanel.getLayout()).show(acabaPanel, "surtCard");
        } catch (ExcepcioKenken e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_solucioButtonActionPerformed

    private void disableButtons() {
        pausaButton.setEnabled(false);
        reanudaButton.setEnabled(false);
        pistaButton.setEnabled(false);
        solucioButton.setEnabled(false);
        disableNumPad();
        valorButton.setEnabled(false);
        notesButton.setEnabled(false);
    }

    private void disableNumPad() {
        for (JToggleButton button : buttonArray) {
            button.setEnabled(false);
        }
    }

    private void reanudaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reanudaButtonActionPerformed
        CtrlPresentacio.comencaTemps();
        reanudaButton.setVisible(false); // hide the resume button
        pausaButton.setVisible(true); // show the pause button

        // Enable all buttons in the buttonArray
        for (JToggleButton button : buttonArray) {
            button.setEnabled(true);
        }
    }//GEN-LAST:event_reanudaButtonActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        numPadPressed(1);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        numPadPressed(2);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        numPadPressed(3);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        numPadPressed(4);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        numPadPressed(5);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        numPadPressed(6);
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        numPadPressed(7);
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        numPadPressed(8);
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        numPadPressed(9);
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void guardaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardaButtonActionPerformed
        CtrlPresentacio.guardarJoc();
    }//GEN-LAST:event_guardaButtonActionPerformed

    private void surtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surtButtonActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "No soportaste :(", "Game Over", JOptionPane.DEFAULT_OPTION);
        if (dialogResult == JOptionPane.OK_OPTION) {
            jocPanel.updateListJocs();
            cardLayout.show(mainPanel, "jocCard");
        }
    }//GEN-LAST:event_surtButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acabaPanel;
    private javax.swing.JButton guardaButton;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JPanel kenkenPanel0;
    private javax.swing.JPanel modeOptions;
    private javax.swing.JToggleButton notesButton;
    private javax.swing.JPanel numberPad;
    private javax.swing.JButton pausaButton;
    private javax.swing.JButton pistaButton;
    private javax.swing.JButton reanudaButton;
    private javax.swing.JButton solucioButton;
    private javax.swing.JButton surtButton;
    private javax.swing.JPanel tempsButton;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JPanel toolOptions;
    private javax.swing.JToggleButton valorButton;
    // End of variables declaration//GEN-END:variables

}
