/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package capaPresentacio.views;

import capaDomini.rankings.Ranking.RankingEntry;
import capaPresentacio.CtrlPresentacio;
import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 *
 * @author Usuario
 */
public class rankingView extends javax.swing.JPanel {


    /**
     * Creates new customizer rankingView
     */
    public rankingView() {
        initComponents();
        initRadioButtonListeners();

        mostrarRankingParaNivel(3);
        jRadioButton1.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        filterPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        contentPanel = new javax.swing.JPanel();
        jList1 = new JList<JPanel>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(237, 224, 212));
        setLayout(new java.awt.GridBagLayout());

        filterPanel.setBackground(new java.awt.Color(237, 224, 212));
        filterPanel.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(89, 61, 59));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dificultat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 40, 0);
        filterPanel.add(jLabel2, gridBagConstraints);

        jRadioButton1.setBackground(new java.awt.Color(237, 224, 212));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(89, 61, 59));
        jRadioButton1.setText("3x3");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        filterPanel.add(jRadioButton1, gridBagConstraints);

        jRadioButton2.setBackground(new java.awt.Color(237, 224, 212));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(89, 61, 59));
        jRadioButton2.setText("4x4");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        filterPanel.add(jRadioButton2, gridBagConstraints);

        jRadioButton3.setBackground(new java.awt.Color(237, 224, 212));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(89, 61, 59));
        jRadioButton3.setText("5x5");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        filterPanel.add(jRadioButton3, gridBagConstraints);

        jRadioButton4.setBackground(new java.awt.Color(237, 224, 212));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(89, 61, 59));
        jRadioButton4.setText("9x9");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        filterPanel.add(jRadioButton4, gridBagConstraints);

        jRadioButton5.setBackground(new java.awt.Color(237, 224, 212));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(89, 61, 59));
        jRadioButton5.setText("6x6");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        filterPanel.add(jRadioButton5, gridBagConstraints);

        jRadioButton6.setBackground(new java.awt.Color(237, 224, 212));
        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(89, 61, 59));
        jRadioButton6.setText("7x7");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        filterPanel.add(jRadioButton6, gridBagConstraints);

        jRadioButton7.setBackground(new java.awt.Color(237, 224, 212));
        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(89, 61, 59));
        jRadioButton7.setText("8x8");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        filterPanel.add(jRadioButton7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -3;
        add(filterPanel, gridBagConstraints);

        contentPanel.setBackground(new java.awt.Color(237, 224, 212));
        contentPanel.setLayout(new java.awt.GridBagLayout());

        jList1.setBackground(new java.awt.Color(237, 224, 212));
        jList1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(1, 1, 1));
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 0, 100);
        contentPanel.add(jList1, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(171, 148, 126));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("<-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        contentPanel.add(jButton1, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(171, 148, 126));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        contentPanel.add(jButton2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(contentPanel, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(89, 61, 59));
        jLabel1.setText("Ranking");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 40, 0);
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        mostrarRankingParaNivel(3);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        mostrarRankingParaNivel(5);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        mostrarRankingParaNivel(4);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        mostrarRankingParaNivel(6);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        mostrarRankingParaNivel(7);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        mostrarRankingParaNivel(8);
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        mostrarRankingParaNivel(9);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (rankingList != null && currentPage > 0) {
            currentPage--;
            updateListModel();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (rankingList != null && (currentPage + 1) * ENTRIES_PER_PAGE < rankingList.size()) {
            currentPage++;
            updateListModel();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private int currentPage = 0;
    private static final int ENTRIES_PER_PAGE = 10;
    private List<RankingEntry> rankingList;
    private String loggedUser;

    private void mostrarRankingParaNivel(int nivel) {
        rankingList = CtrlPresentacio.getRankingPerDificultat(nivel);
        loggedUser = CtrlPresentacio.getNombreUsuarioLoggeado();

        currentPage = 0;
        updateListModel();
    }

    // Custom renderer for JPanel in JList
    private static class JPanelRenderer implements ListCellRenderer<JPanel> {
        @Override
        public Component getListCellRendererComponent(JList<? extends JPanel> list, JPanel value, int index, boolean isSelected, boolean cellHasFocus) {
            if (isSelected) {
                value.setBackground(new Color(237, 224, 212)); // Color de fondo para el panel seleccionado
            } else {
                value.setBackground(new Color(237, 224, 212)); // Color de fondo para el panel no seleccionado
            }
            return value;
        }
    }

    private void updateListModel() {
        DefaultListModel<JPanel> listModel = new DefaultListModel<>();
        if (rankingList != null && !rankingList.isEmpty()) {
            JPanel headerPanel = new JPanel(new GridLayout(1, 3, 10, 0)); // 10px horizontal gap
            headerPanel.setBackground(new Color(237, 224, 212));
            headerPanel.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK),
                    BorderFactory.createEmptyBorder(10, 20, 10, 20) // top, left, bottom, right margins
            ));

            JLabel posicioLabel = new JLabel("Posició");
            posicioLabel.setHorizontalAlignment(SwingConstants.LEFT);
            posicioLabel.setFont(new Font("Segoe UI", Font.BOLD, 16));
            posicioLabel.setForeground(Color.BLACK);

            JLabel jugadorLabel = new JLabel("Jugador");
            jugadorLabel.setHorizontalAlignment(SwingConstants.CENTER);
            jugadorLabel.setFont(new Font("Segoe UI", Font.BOLD, 16));
            jugadorLabel.setForeground(Color.BLACK);

            JLabel tiempoLabel = new JLabel("Millor temps");
            tiempoLabel.setHorizontalAlignment(SwingConstants.RIGHT);
            tiempoLabel.setFont(new Font("Segoe UI", Font.BOLD, 16));
            tiempoLabel.setForeground(Color.BLACK);

            headerPanel.add(posicioLabel);
            headerPanel.add(jugadorLabel);
            headerPanel.add(tiempoLabel);
            listModel.addElement(headerPanel);

            int start = currentPage * ENTRIES_PER_PAGE;
            int end = Math.min(start + ENTRIES_PER_PAGE, rankingList.size());
            for (int i = start; i < end; i++) {
                RankingEntry entry = rankingList.get(i);
                long totalMillis = entry.getBestTime();
                long minutes = totalMillis / 60000;
                long seconds = (totalMillis % 60000) / 1000;
                long millis = totalMillis % 1000;
                String time = String.format("%02d:%02d.%03d", minutes, seconds, millis);

                String usernameColor = entry.getUsername().equals(loggedUser) ? "#FF5733" : "#6178FF";

                JPanel rowPanel = new JPanel(new GridLayout(1, 3, 10, 0)); // 10px horizontal gap
                rowPanel.setBackground(new Color(237, 224, 212));
                rowPanel.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY),
                        BorderFactory.createEmptyBorder(10, 20, 10, 20) // top, left, bottom, right margins
                ));

                JLabel positionLabel = new JLabel(Integer.toString(i + 1));
                positionLabel.setHorizontalAlignment(SwingConstants.LEFT);
                positionLabel.setFont(new Font("Segoe UI", Font.PLAIN, 14));

                JLabel userLabel = new JLabel("<html><font color='" + usernameColor + "'>" + entry.getUsername() + "</font></html>");
                userLabel.setHorizontalAlignment(SwingConstants.CENTER);
                userLabel.setFont(new Font("Segoe UI", Font.PLAIN, 14));

                JLabel timeLabel = new JLabel("<html><font color='#FF7658'>" + time + "</font></html>");
                timeLabel.setHorizontalAlignment(SwingConstants.RIGHT);
                timeLabel.setFont(new Font("Segoe UI", Font.PLAIN, 14));

                rowPanel.add(positionLabel);
                rowPanel.add(userLabel);
                rowPanel.add(timeLabel);
                listModel.addElement(rowPanel);
            }
        } else {
            JPanel noDataPanel = new JPanel();
            noDataPanel.setBackground(new Color(237, 224, 212));
            noDataPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
            JLabel noDataLabel = new JLabel("No hi ha dades disponibles per aquest nivell.");
            noDataLabel.setFont(new Font("Segoe UI", Font.ITALIC, 14));
            noDataLabel.setHorizontalAlignment(SwingConstants.CENTER);
            noDataPanel.add(noDataLabel);
            listModel.addElement(noDataPanel);
        }
        jList1.setModel(listModel);
        jList1.setCellRenderer(new JPanelRenderer());
        jList1.revalidate(); // To ensure the list is revalidated
        jList1.repaint(); // To ensure the list is repainted
    }

    private void initRadioButtonListeners() {
        jRadioButton1.addActionListener(e -> mostrarRankingParaNivel(3));
        jRadioButton2.addActionListener(e -> mostrarRankingParaNivel(4));
        jRadioButton3.addActionListener(e -> mostrarRankingParaNivel(5));
        jRadioButton4.addActionListener(e -> mostrarRankingParaNivel(6));
        jRadioButton5.addActionListener(e -> mostrarRankingParaNivel(7));
        jRadioButton6.addActionListener(e -> mostrarRankingParaNivel(8));
        jRadioButton7.addActionListener(e -> mostrarRankingParaNivel(9));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private JList<JPanel> jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    // End of variables declaration//GEN-END:variables
}