/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package capaPresentacio.views;

import capaDomini.excepcions.ExcepcioUsuari;
import capaPresentacio.CtrlPresentacio;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author linhu
 */
public class signupPanel extends javax.swing.JPanel {
    //mainPanel es el panel de loginView
    //parentFrame es la ventana entera de loginView
    private final javax.swing.JPanel mainPanel;
    private final JFrame parentFrame;
    /**
     * Creates new form signupPanel
     */
    public signupPanel(javax.swing.JPanel mainPanel, JFrame parentFrame) {
        this.mainPanel = mainPanel;
        this.parentFrame = parentFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        inputPanel = new javax.swing.JPanel();
        usernamePanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        password1Box = new javax.swing.JPanel();
        password1Label = new javax.swing.JLabel();
        password1Field = new javax.swing.JPasswordField();
        password2Box = new javax.swing.JPanel();
        password2Label = new javax.swing.JLabel();
        password2Field = new javax.swing.JPasswordField();
        createButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(237, 224, 212));
        setLayout(new java.awt.GridBagLayout());

        inputPanel.setLayout(new java.awt.GridLayout(0, 1));

        usernamePanel.setBackground(new java.awt.Color(237, 224, 212));
        usernamePanel.setLayout(new java.awt.GridLayout(2, 0));

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(127, 85, 57));
        usernameLabel.setText("Nom d'usuari");
        usernamePanel.add(usernameLabel);

        usernameField.setForeground(new java.awt.Color(127, 85, 57));
        usernameField.setBorder(null);
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        usernamePanel.add(usernameField);

        inputPanel.add(usernamePanel);

        password1Box.setBackground(new java.awt.Color(237, 224, 212));
        password1Box.setLayout(new java.awt.GridLayout(2, 0));

        password1Label.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        password1Label.setForeground(new java.awt.Color(127, 85, 57));
        password1Label.setText("Contrasenya");
        password1Box.add(password1Label);

        password1Field.setForeground(new java.awt.Color(127, 85, 57));
        password1Field.setBorder(null);
        password1Box.add(password1Field);

        inputPanel.add(password1Box);

        password2Box.setBackground(new java.awt.Color(237, 224, 212));
        password2Box.setLayout(new java.awt.GridLayout(2, 0));

        password2Label.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        password2Label.setForeground(new java.awt.Color(127, 85, 57));
        password2Label.setText("Repetir contrasenya");
        password2Box.add(password2Label);

        password2Field.setForeground(new java.awt.Color(127, 85, 57));
        password2Field.setBorder(null);
        password2Box.add(password2Field);

        inputPanel.add(password2Box);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 180;
        gridBagConstraints.ipady = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 0, 0, 85);
        add(inputPanel, gridBagConstraints);

        createButton.setBackground(new java.awt.Color(171, 148, 126));
        createButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createButton.setForeground(new java.awt.Color(237, 224, 212));
        createButton.setText("Crear compte");
        createButton.setBorder(null);
        createButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 71, 59, 0);
        add(createButton, gridBagConstraints);

        loginButton.setBackground(new java.awt.Color(171, 148, 126));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginButton.setForeground(new java.awt.Color(237, 224, 212));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        add(loginButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(ActionEvent evt) {

    }

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String username = usernameField.getText();
        String password1 = new String(password1Field.getPassword());
        String password2 = new String(password2Field.getPassword());
        if (!password1.equals(password2)) {
            JOptionPane.showMessageDialog(this, "Les contrasenyes no coincideixen");
            return;
        }
        try {
            CtrlPresentacio.crearUsuari(username, password1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            return;
        }
        //crea ventana principal del juego
        mainView mv = new mainView();
        mv.setVisible(true);
        //elimina la ventana de login
        this.parentFrame.dispose();
    }//GEN-LAST:event_createButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:

            Window window = SwingUtilities.getWindowAncestor(this);
            if (window != null) {
                window.dispose();
            }
            CtrlPresentacio.ini();
    }//GEN-LAST:event_loginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel password1Box;
    private javax.swing.JPasswordField password1Field;
    private javax.swing.JLabel password1Label;
    private javax.swing.JPanel password2Box;
    private javax.swing.JPasswordField password2Field;
    private javax.swing.JLabel password2Label;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JPanel usernamePanel;
    // End of variables declaration//GEN-END:variables
}
