/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package capaPresentacio.views;

import capaPresentacio.CtrlPresentacio;
import capaDomini.excepcions.ExcepcioUsuari;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Usuario
 */
public class usersPanel extends javax.swing.JPanel implements java.beans.Customizer {

    private Object bean;
    private final CardLayout cardLayout;
    private final JPanel cardPanel;

    /**
     * Creates new customizer usersView
     */
    public usersPanel() {
        initComponents();

        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);

        cardPanel.add(jPanelPerfilGestio, "jPanelPerfilGestio");
        cardPanel.add(jpanelEstadistiques, "jpanelEstadistiques");

        setLayout(new BorderLayout());
        add(cardPanel, BorderLayout.CENTER);

        // Add buttons to a separate panel for navigation
        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridLayout(2, 1, 10, 10));
        buttonPanel.add(jButtonEstadistiques);
        buttonPanel.add(ProfileButton);
        add(buttonPanel, BorderLayout.WEST);

        //stats
        showStats();
    }

    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        optionPanel = new javax.swing.JPanel();
        ProfileButton = new javax.swing.JButton();
        jButtonEstadistiques = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        jPanelPerfilGestio = new javax.swing.JPanel();
        canviaBox = new javax.swing.JPanel();
        ContrasenyaActualjLabel = new javax.swing.JLabel();
        RepeatPwjLabel = new javax.swing.JLabel();
        NewPWjLabel = new javax.swing.JLabel();
        ActualPasswordField = new javax.swing.JPasswordField();
        RepeatPasswordField = new javax.swing.JPasswordField();
        NewPwPasswordField = new javax.swing.JPasswordField();
        consultaLabel = new javax.swing.JLabel();
        canviaLabel = new javax.swing.JLabel();
        deleteProfileToggleButton = new javax.swing.JToggleButton();
        canviaToggleButtonChangePassword = new javax.swing.JToggleButton();
        getPasswordjButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jpanelEstadistiques = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TotalLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayTotalKenkensTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        MillorTempsLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MillorTempsDTextArea = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        MitjanaTempsLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        MitjaTempsTextArea = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        StatsPerNivellsLabel = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TotalJugatsTextArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        BestTempsUserTextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        MitjanaTempsTextArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(237, 224, 212));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setLayout(new java.awt.GridBagLayout());

        optionPanel.setLayout(new java.awt.GridLayout(2, 0));

        ProfileButton.setBackground(new java.awt.Color(171, 148, 126));
        ProfileButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ProfileButton.setForeground(new java.awt.Color(237, 224, 212));
        ProfileButton.setText("Gestionar Perfil");
        ProfileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileButtonActionPerformed(evt);
            }
        });
        optionPanel.add(ProfileButton);

        jButtonEstadistiques.setBackground(new java.awt.Color(171, 148, 126));
        jButtonEstadistiques.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonEstadistiques.setForeground(new java.awt.Color(237, 224, 212));
        jButtonEstadistiques.setText("Estadístiques");
        jButtonEstadistiques.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEstadistiques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstadistiquesActionPerformed(evt);
            }
        });
        optionPanel.add(jButtonEstadistiques);

        add(optionPanel, new java.awt.GridBagConstraints());

        contentPanel.setLayout(new java.awt.CardLayout());

        jPanelPerfilGestio.setBackground(new java.awt.Color(237, 224, 212));
        jPanelPerfilGestio.setLayout(new java.awt.GridBagLayout());

        canviaBox.setBackground(new java.awt.Color(237, 224, 212));
        canviaBox.setLayout(new java.awt.GridBagLayout());

        ContrasenyaActualjLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ContrasenyaActualjLabel.setForeground(new java.awt.Color(89, 61, 59));
        ContrasenyaActualjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ContrasenyaActualjLabel.setText("Contrasenya actual");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        canviaBox.add(ContrasenyaActualjLabel, gridBagConstraints);

        RepeatPwjLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RepeatPwjLabel.setForeground(new java.awt.Color(89, 61, 59));
        RepeatPwjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RepeatPwjLabel.setText("Repetir nova contrasenya");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        canviaBox.add(RepeatPwjLabel, gridBagConstraints);

        NewPWjLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewPWjLabel.setForeground(new java.awt.Color(89, 61, 59));
        NewPWjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NewPWjLabel.setText("Nova contrasenya");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        canviaBox.add(NewPWjLabel, gridBagConstraints);

        ActualPasswordField.setForeground(new java.awt.Color(89, 61, 59));
        ActualPasswordField.setBorder(null);
        ActualPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualPasswordFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = 20;
        canviaBox.add(ActualPasswordField, gridBagConstraints);

        RepeatPasswordField.setForeground(new java.awt.Color(89, 61, 59));
        RepeatPasswordField.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 20;
        canviaBox.add(RepeatPasswordField, gridBagConstraints);

        NewPwPasswordField.setForeground(new java.awt.Color(89, 61, 59));
        NewPwPasswordField.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 20;
        canviaBox.add(NewPwPasswordField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 200);
        jPanelPerfilGestio.add(canviaBox, gridBagConstraints);

        consultaLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        consultaLabel.setForeground(new java.awt.Color(89, 61, 59));
        consultaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consultaLabel.setText("Consultar Contrasenya");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 200;
        jPanelPerfilGestio.add(consultaLabel, gridBagConstraints);

        canviaLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        canviaLabel.setForeground(new java.awt.Color(89, 61, 59));
        canviaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        canviaLabel.setText("Canviar Contrasenya");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 200);
        jPanelPerfilGestio.add(canviaLabel, gridBagConstraints);

        deleteProfileToggleButton.setBackground(new java.awt.Color(191, 67, 66));
        deleteProfileToggleButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deleteProfileToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteProfileToggleButton.setText("Eliminar Perfil");
        deleteProfileToggleButton.setBorder(null);
        deleteProfileToggleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteProfileToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProfileToggleButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        jPanelPerfilGestio.add(deleteProfileToggleButton, gridBagConstraints);

        canviaToggleButtonChangePassword.setBackground(new java.awt.Color(171, 148, 126));
        canviaToggleButtonChangePassword.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        canviaToggleButtonChangePassword.setForeground(new java.awt.Color(237, 224, 212));
        canviaToggleButtonChangePassword.setText("Canviar");
        canviaToggleButtonChangePassword.setBorder(null);
        canviaToggleButtonChangePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        canviaToggleButtonChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canviaToggleButtonChangePasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 200);
        jPanelPerfilGestio.add(canviaToggleButtonChangePassword, gridBagConstraints);

        getPasswordjButton.setBackground(new java.awt.Color(171, 148, 126));
        getPasswordjButton.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        getPasswordjButton.setForeground(new java.awt.Color(237, 224, 212));
        getPasswordjButton.setText("Apreta aqui");
        getPasswordjButton.setBorder(null);
        getPasswordjButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getPasswordjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPasswordjButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        jPanelPerfilGestio.add(getPasswordjButton, gridBagConstraints);

        logoutButton.setBackground(new java.awt.Color(171, 148, 126));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(237, 224, 212));
        logoutButton.setText("Log Out");
        logoutButton.setBorder(null);
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        jPanelPerfilGestio.add(logoutButton, gridBagConstraints);

        contentPanel.add(jPanelPerfilGestio, "card4");

        jpanelEstadistiques.setBackground(new java.awt.Color(237, 224, 212));
        jpanelEstadistiques.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Estadístiques");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 109;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 358, 0, 0);
        jpanelEstadistiques.add(jLabel7, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(237, 224, 212));

        TotalLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalLabel.setText("Total Kenkens Jugats");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        DisplayTotalKenkensTextArea.setEditable(false);
        DisplayTotalKenkensTextArea.setBackground(new java.awt.Color(237, 224, 212));
        DisplayTotalKenkensTextArea.setColumns(20);
        DisplayTotalKenkensTextArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DisplayTotalKenkensTextArea.setRows(5);
        jScrollPane1.setViewportView(DisplayTotalKenkensTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(TotalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 428, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(TotalLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 422;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jpanelEstadistiques.add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(237, 224, 212));

        MillorTempsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MillorTempsLabel.setText("Millor Temps Absolut");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        MillorTempsDTextArea.setEditable(false);
        MillorTempsDTextArea.setBackground(new java.awt.Color(237, 224, 212));
        MillorTempsDTextArea.setColumns(20);
        MillorTempsDTextArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MillorTempsDTextArea.setRows(5);
        jScrollPane2.setViewportView(MillorTempsDTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(MillorTempsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 412, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MillorTempsLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 406;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 0);
        jpanelEstadistiques.add(jPanel2, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(237, 224, 212));

        MitjanaTempsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MitjanaTempsLabel.setText("Mitjana Temps Global");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        MitjaTempsTextArea.setEditable(false);
        MitjaTempsTextArea.setBackground(new java.awt.Color(237, 224, 212));
        MitjaTempsTextArea.setColumns(20);
        MitjaTempsTextArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MitjaTempsTextArea.setRows(5);
        jScrollPane3.setViewportView(MitjaTempsTextArea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(MitjanaTempsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(MitjanaTempsLabel)))
                .addGap(16, 16, 16))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 414;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        jpanelEstadistiques.add(jPanel5, gridBagConstraints);

        jPanel6.setBackground(new java.awt.Color(237, 224, 212));

        StatsPerNivellsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        StatsPerNivellsLabel.setText("Estadistiques per Nivells");

        jRadioButton1.setBackground(new java.awt.Color(237, 224, 212));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("3x3");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(237, 224, 212));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("4x4");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(237, 224, 212));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("5x5");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setBackground(new java.awt.Color(237, 224, 212));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("6x6");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setBackground(new java.awt.Color(237, 224, 212));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("7x7");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setBackground(new java.awt.Color(237, 224, 212));
        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("8x8");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton7.setBackground(new java.awt.Color(237, 224, 212));
        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("9x9");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Total Jugats");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Millor Temps");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Mitjana Temps");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TotalJugatsTextArea.setEditable(false);
        TotalJugatsTextArea.setBackground(new java.awt.Color(237, 224, 212));
        TotalJugatsTextArea.setColumns(20);
        TotalJugatsTextArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalJugatsTextArea.setRows(5);
        jScrollPane4.setViewportView(TotalJugatsTextArea);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        BestTempsUserTextArea.setEditable(false);
        BestTempsUserTextArea.setBackground(new java.awt.Color(237, 224, 212));
        BestTempsUserTextArea.setColumns(20);
        BestTempsUserTextArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BestTempsUserTextArea.setRows(5);
        jScrollPane5.setViewportView(BestTempsUserTextArea);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        MitjanaTempsTextArea.setEditable(false);
        MitjanaTempsTextArea.setBackground(new java.awt.Color(237, 224, 212));
        MitjanaTempsTextArea.setColumns(20);
        MitjanaTempsTextArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MitjanaTempsTextArea.setRows(5);
        jScrollPane6.setViewportView(MitjanaTempsTextArea);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton6)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButton1)
                                .addComponent(jRadioButton3)
                                .addComponent(jRadioButton4)
                                .addComponent(jRadioButton5)
                                .addComponent(jRadioButton2))
                            .addComponent(jRadioButton7)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(StatsPerNivellsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(29, 29, 29)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(34, 34, 34))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(StatsPerNivellsLabel)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jRadioButton3)
                                .addGap(7, 7, 7)
                                .addComponent(jRadioButton4))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton7)
                        .addGap(39, 39, 39))))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 176;
        gridBagConstraints.ipady = -45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 19, 88, 0);
        jpanelEstadistiques.add(jPanel6, gridBagConstraints);

        contentPanel.add(jpanelEstadistiques, "card3");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(contentPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteProfileToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProfileToggleButtonActionPerformed
        JPasswordField pf = new JPasswordField();
        int okCxl = JOptionPane.showConfirmDialog(null, pf, "Introduir contrasenya", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (okCxl == JOptionPane.OK_OPTION) {
            String contrasenyaActual = new String(pf.getPassword());
            int confirmed = JOptionPane.showConfirmDialog(null,
                    "Estàs segur de que vols eliminar el teu perfil? Aquesta acció no es pot desfer.", "Eliminar Perfil",
                    JOptionPane.YES_NO_OPTION);

            if (confirmed == JOptionPane.YES_OPTION) {
                try {
                    if (CtrlPresentacio.comprovarContrasenya(contrasenyaActual)) {
                        CtrlPresentacio.eliminarPerfilUsuario(contrasenyaActual);
                        JOptionPane.showMessageDialog(null, "Perfil eliminat.");
                        // Cerrar la ventana actual
                        Window window = SwingUtilities.getWindowAncestor(this);
                        if (window != null) {
                            window.dispose();
                        }
                        CtrlPresentacio.ini();
                    } else {
                        JOptionPane.showMessageDialog(null, "La contrasenya es incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (ExcepcioUsuari e) {
                    JOptionPane.showMessageDialog(null, "Error en eliminar el perfil: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_deleteProfileToggleButtonActionPerformed

    private void canviaToggleButtonChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canviaToggleButtonChangePasswordActionPerformed
        changePasswordActionPerformed(evt);
    }//GEN-LAST:event_canviaToggleButtonChangePasswordActionPerformed

    private void jButtonEstadistiquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstadistiquesActionPerformed
        //estadistiques
        CardLayout card = (CardLayout) cardPanel.getLayout();
        card.show(cardPanel, "jpanelEstadistiques");
        SwingUtilities.invokeLater(() -> {
            showStats();
        });
    }//GEN-LAST:event_jButtonEstadistiquesActionPerformed

    private void ProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileButtonActionPerformed
        CardLayout card = (CardLayout) cardPanel.getLayout();
        card.show(cardPanel, "jPanelPerfilGestio");
    }//GEN-LAST:event_ProfileButtonActionPerformed

    private void getPasswordjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPasswordjButtonActionPerformed
        // TODO add your handling code here:
        //consultar contrasenya actual
        String Pass = CtrlPresentacio.getPassword(); // Asegúrate de que este método devuelve la nueva contraseña
        JOptionPane.showMessageDialog(this, "La teva contrasenya actual es: " + Pass);
    }//GEN-LAST:event_getPasswordjButtonActionPerformed

    private void ActualPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualPasswordFieldActionPerformed

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

        int nivell = 3;
        int total = CtrlPresentacio.getKenkensJugatsPerNivell(nivell);
        String st = Integer.toString(total);
        TotalJugatsTextArea.setText(st);

        Long millor = CtrlPresentacio.getMillorTempsPerNivell(nivell);
        String best = formatTime(millor);
        BestTempsUserTextArea.setText(best);

        Long mitja = CtrlPresentacio.getMitjanaTempsPerNivell(nivell);
        String m = formatTime(mitja);
        MitjanaTempsTextArea.setText(m);

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        int nivell = 4;
        int total = CtrlPresentacio.getKenkensJugatsPerNivell(nivell);
        String st = Integer.toString(total);
        TotalJugatsTextArea.setText(st);

        Long millor = CtrlPresentacio.getMillorTempsPerNivell(nivell);
        String best = formatTime(millor);
        BestTempsUserTextArea.setText(best);

        Long mitja = CtrlPresentacio.getMitjanaTempsPerNivell(nivell);
        String m = formatTime(mitja);
        MitjanaTempsTextArea.setText(m);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        int nivell = 5;
        int total = CtrlPresentacio.getKenkensJugatsPerNivell(nivell);
        String st = Integer.toString(total);
        TotalJugatsTextArea.setText(st);

        Long millor = CtrlPresentacio.getMillorTempsPerNivell(nivell);
        String best = formatTime(millor);
        BestTempsUserTextArea.setText(best);

        Long mitja = CtrlPresentacio.getMitjanaTempsPerNivell(nivell);
        String m = formatTime(mitja);
        MitjanaTempsTextArea.setText(m);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        int nivell = 6;
        int total = CtrlPresentacio.getKenkensJugatsPerNivell(nivell);
        String st = Integer.toString(total);
        TotalJugatsTextArea.setText(st);

        Long millor = CtrlPresentacio.getMillorTempsPerNivell(nivell);
        String best = formatTime(millor);
        BestTempsUserTextArea.setText(best);

        Long mitja = CtrlPresentacio.getMitjanaTempsPerNivell(nivell);
        String m = formatTime(mitja);
        MitjanaTempsTextArea.setText(m);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        int nivell = 7;
        int total = CtrlPresentacio.getKenkensJugatsPerNivell(nivell);
        String st = Integer.toString(total);
        TotalJugatsTextArea.setText(st);

        Long millor = CtrlPresentacio.getMillorTempsPerNivell(nivell);
        String best = formatTime(millor);
        BestTempsUserTextArea.setText(best);

        Long mitja = CtrlPresentacio.getMitjanaTempsPerNivell(nivell);
        String m = formatTime(mitja);
        MitjanaTempsTextArea.setText(m);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
       int nivell = 8;
        int total = CtrlPresentacio.getKenkensJugatsPerNivell(nivell);
        String st = Integer.toString(total);
        TotalJugatsTextArea.setText(st);

        Long millor = CtrlPresentacio.getMillorTempsPerNivell(nivell);
        String best = formatTime(millor);
        BestTempsUserTextArea.setText(best);

        Long mitja = CtrlPresentacio.getMitjanaTempsPerNivell(nivell);
        String m = formatTime(mitja);
        MitjanaTempsTextArea.setText(m);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        int nivell = 9;
        int total = CtrlPresentacio.getKenkensJugatsPerNivell(nivell);
        String st = Integer.toString(total);
        TotalJugatsTextArea.setText(st);

        Long millor = CtrlPresentacio.getMillorTempsPerNivell(nivell);
        String best = formatTime(millor);
        BestTempsUserTextArea.setText(best);

        Long mitja = CtrlPresentacio.getMitjanaTempsPerNivell(nivell);
        String m = formatTime(mitja);
        MitjanaTempsTextArea.setText(m);
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        try {
            CtrlPresentacio.logout();
            // Cerrar la ventana actual
            Window window = SwingUtilities.getWindowAncestor(this);
            if (window != null) {
                window.dispose();
            }
            CtrlPresentacio.ini();
        } catch (ExcepcioUsuari e) {
            JOptionPane.showMessageDialog(null, "Error en eliminar el perfil: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void changePasswordActionPerformed(java.awt.event.ActionEvent evt) {
        String currentPassword = new String(ActualPasswordField.getPassword());
        String newPassword = new String(RepeatPasswordField.getPassword());
        String repeatNewPassword = new String(NewPwPasswordField.getPassword());

        if (!newPassword.equals(repeatNewPassword)) {
            JOptionPane.showMessageDialog(this, "La nova contrasenya no coincideix.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (newPassword.equals("")) {
            JOptionPane.showMessageDialog(this, "La nova contrasenya no pot ser buida.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            if (CtrlPresentacio.comprovarContrasenya(currentPassword)) {
                CtrlPresentacio.canviarContrasenya(currentPassword, newPassword);
                JOptionPane.showMessageDialog(this, "Contrasenya canviada amb exit.");
            } else {
                JOptionPane.showMessageDialog(this, "La contrasenya actual es incorrecta.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ExcepcioUsuari e) {
            JOptionPane.showMessageDialog(this, "Error al canviar la contrasenya: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    /**
     * @brief Muestra las estadísticas del usuario logueado
     */
    public static void showStats() {
        try {
            // Obtener el nombre del usuario logueado
            String username = CtrlPresentacio.getNombreUsuarioLoggeado();
            if (username == null) {
                return;
            }

            // Obtener las estadísticas del usuario
            Integer kenkensJugats = CtrlPresentacio.getKenkensJugats();
            if (kenkensJugats != null) {
                DisplayTotalKenkensTextArea.setText(kenkensJugats.toString());
            } else {
                DisplayTotalKenkensTextArea.setText("0");
            }

            Long millorTemps = CtrlPresentacio.getMillorTempsAbsolut();
            if (millorTemps != null) {
                String millorTempsFormatted = formatTime(millorTemps);
                MillorTempsDTextArea.setText(millorTempsFormatted);
            } else {
                MillorTempsDTextArea.setText("00:00.000");
            }

            Long mitjanaTemps = CtrlPresentacio.getMitjanaTempsAbsolut();
            if (mitjanaTemps != null) {
                String mitjanaTempsFormatted = formatTime(mitjanaTemps);
                MitjaTempsTextArea.setText(mitjanaTempsFormatted);
            } else {
                MitjaTempsTextArea.setText("00:00.000");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @brief Formatea un tiempo en milisegundos a un string en formato mm:ss:SSS
     * @param timeInMillis Tiempo en milisegundos
     * @return Tiempo formateado en formato mm:ss:SSS
     */
    static String formatTime(long timeInMillis) {
        long minutes = (timeInMillis / 60000);
        long seconds = (timeInMillis % 60000) / 1000;
        long milliseconds = timeInMillis % 1000;

        return String.format("%02d:%02d:%03d", minutes, seconds, milliseconds);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ActualPasswordField;
    private javax.swing.JTextArea BestTempsUserTextArea;
    private javax.swing.JLabel ContrasenyaActualjLabel;
    private static javax.swing.JTextArea DisplayTotalKenkensTextArea;
    private static javax.swing.JTextArea MillorTempsDTextArea;
    private javax.swing.JLabel MillorTempsLabel;
    private static javax.swing.JTextArea MitjaTempsTextArea;
    private javax.swing.JLabel MitjanaTempsLabel;
    private javax.swing.JTextArea MitjanaTempsTextArea;
    private javax.swing.JLabel NewPWjLabel;
    private javax.swing.JPasswordField NewPwPasswordField;
    private javax.swing.JButton ProfileButton;
    private javax.swing.JPasswordField RepeatPasswordField;
    private javax.swing.JLabel RepeatPwjLabel;
    private javax.swing.JLabel StatsPerNivellsLabel;
    private javax.swing.JTextArea TotalJugatsTextArea;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel canviaBox;
    private javax.swing.JLabel canviaLabel;
    private javax.swing.JToggleButton canviaToggleButtonChangePassword;
    private javax.swing.JLabel consultaLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JToggleButton deleteProfileToggleButton;
    private javax.swing.JButton getPasswordjButton;
    private javax.swing.JButton jButtonEstadistiques;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelPerfilGestio;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel jpanelEstadistiques;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel optionPanel;
    // End of variables declaration//GEN-END:variables
}
